config/routes.rb
Rails.application.routes.draw do
  resources :acessos

  resources :menusubs

  resources :menus

  devise_for :users
  get 'inicio/index'
  match "inicio/index" => "inicio#index", :via => :post
  get 'inicio/detalhes'

  get 'aprovacao/index'

  get 'aprovacao/aprovacao' => 'aprovacao#aprovacao', :as => :aprovacao

  resources :pagamentos

  resources :lancamentoprodutos

  resources :lancamentos

  resources :orcamentos

  resources :produtos

  resources :fornecedores

  resources :obras

  get 'paginas/home'

  root 'inicio#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    @Acesso = Acesso.where('user_id=?',user.id)
    if(user.id == 1)
      can :manage, :all
    else
      @Acesso.each do |acesso|

        can acesso.acao.to_sym, acesso.menusub.modulo.constantize
      end

    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/acesso.rb
class Acesso < ActiveRecord::Base
  belongs_to :user
  belongs_to :menusub
end

app/models/aprovacao.rb
class Aprovacao

end

app/models/cid.rb
class Cid < ActiveRecord::Base
end

app/models/fornecedore.rb
class Fornecedore < ActiveRecord::Base
end

app/models/inicio.rb
class Inicio
  attr_accessor :dataR

  def initialize(dataR)
    @dataR = dataR
  end

end

app/models/lancamento.rb
class Lancamento < ActiveRecord::Base

  has_many :pagamentos
end

app/models/menu.rb
class Menu < ActiveRecord::Base

  has_many :menusub
  has_many :acesso

end

app/models/menusub.rb
class Menusub < ActiveRecord::Base
  belongs_to :menu
  has_many :acesso
end

app/models/obra.rb
class Obra < ActiveRecord::Base
end

app/models/orcamento.rb
class Orcamento < ActiveRecord::Base
end

app/models/pagamento.rb
class Pagamento < ActiveRecord::Base
  attr_accessor :parcelas, :datav, :prazo
  belongs_to :lancamento
end

app/models/produto.rb
class Produto < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :acesso
end

app/controllers/lancamentos_controller.rb
class LancamentosController < ApplicationController
  before_action :set_lancamento, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  respond_to :html

  def index
    @lancamentos = Lancamento.order('created_at desc').all
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'Lancamentos',
               layout: 'layouts/application.pdf.erb',
               :footer => {:right => '[page] de [topage]'},
               show_as_html: params[:debug].present?
      end
    end
  end

  def show
    respond_with(@lancamento)
  end

  def new
    @lancamento = Lancamento.new
    respond_with(@lancamento)
  end

  def edit
  end

  def create
    @lancamento = Lancamento.new(lancamento_params)
    @lancamento.save
    respond_with(@lancamento)
  end

  def update
    @lancamento.update(lancamento_params)
    respond_with(@lancamento)
  end

  def destroy
    @lancamento.destroy
    respond_with(@lancamento)
  end

  private
    def set_lancamento
      @lancamento = Lancamento.find(params[:id])
    end

    def lancamento_params
      params.require(:lancamento).permit(:obra, :fornecedor, :nota, :valor, :status)
    end
end

app/helpers/acessos_helper.rb
module AcessosHelper
end

app/helpers/cids_helper.rb
module CidsHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/lancamentos_helper.rb
module LancamentosHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/menusubs_helper.rb
module MenusubsHelper
end

app/helpers/obras_helper.rb
module ObrasHelper
end

app/helpers/paginas_helper.rb
module PaginasHelper
end

app/views/lancamentos/_form.html.erb
<%= form_for @lancamento, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :obra, :class => 'control-label' %>
    <%= f.collection_select(:obra,Obra.order(:obra),:id,:obra,{:prompt=>false},{:class => 'form-control'}) %>
  </div>
  <div class="form-group">
    <%= f.label :fornecedor, :class => 'control-label' %>
    <%= f.collection_select(:fornecedor,Fornecedore.order(:fornecedor),:id,:fornecedor,{:prompt=>false},{:class=>'form-control'}) %>
  </div>
  <div class="form-group">
    <%= f.label :nota, :class => 'control-label' %>
    <%= f.number_field :nota, :class => 'form-control' %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                lancamentos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/lancamentos/cor_form.html.erb
<%= form_for @lancamento, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :obra, :class => 'control-label' %>
    <%= f.number_field :obra, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :fornecedor, :class => 'control-label' %>
    <%= f.number_field :fornecedor, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :nota, :class => 'control-label' %>
    <%= f.number_field :nota, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :valor, :class => 'control-label' %>
    <%= f.text_field :valor, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :status, :class => 'control-label' %>
    <%= f.number_field :status, :class => 'form-control' %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                lancamentos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/lancamentos/edit.html.erb
<%- model_class = Lancamento -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Editar #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/lancamentos/index.html.erb
<%- model_class = Lancamento -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:obra) %></th>
      <th><%= model_class.human_attribute_name(:fornecedor) %></th>
      <th><%= model_class.human_attribute_name(:nota) %></th>
      <th><%= model_class.human_attribute_name(:valor) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @lancamentos.each do |lancamento| %>
      <tr>
        <td><%= link_to lancamento.id, lancamento_path(lancamento) %></td>
        <td><%= Obra.find(lancamento.obra).obra %></td>
        <td><%= Fornecedore.find(lancamento.fornecedor).fornecedor %></td>
        <td><%= lancamento.nota %></td>
        <td><%= number_to_currency(lancamento.valor) %></td>
        <% if(lancamento.status == 0)
              @status = 'Sem Aprovação'
              @cstatus = 'status_v'
              @disable = false
           else
              @status = 'Aprovado'
              @cstatus = 'status_a'
              @disable = true
           end
        %>
        <td class='<%= @cstatus  %>'><%= @status %></td>
        <td><%=l lancamento.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
            edit_lancamento_path(lancamento), :class => 'btn btn-primary btn-xs', :disabled => @disable %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      lancamento_path(lancamento),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger btn-xs', :disabled => @disable %>
                    <%= link_to 'Detalhes',aprovacao_path(:lancamento=>lancamento.id,:voltar=>lancamentos_path),:class => 'btn btn-primary btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_lancamento_path,
            :class => 'btn btn-primary' %>

app/views/lancamentos/index.pdf.erb
<%- model_class = Lancamento -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:obra) %></th>
      <th><%= model_class.human_attribute_name(:fornecedor) %></th>
      <th><%= model_class.human_attribute_name(:nota) %></th>
      <th><%= model_class.human_attribute_name(:valor) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
     </tr>
  </thead>
  <tbody>
    <% @lancamentos.each do |lancamento| %>
      <tr>
        <td><%= lancamento.id %></td>
        <td><%= Obra.find(lancamento.obra).obra %></td>
        <td><%= Fornecedore.find(lancamento.fornecedor).fornecedor %></td>
        <td><%= lancamento.nota %></td>
        <td><%= number_to_currency(lancamento.valor) %></td>
        <% if(lancamento.status == 0)
              @status = 'Sem Aprovação'
              @cstatus = 'status_v'
           else
              @status = 'Aprovado'
              @cstatus = 'status_a'
           end
        %>
        <td class='<%= @cstatus  %>'><%= @status %></td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/lancamentos/new.html.erb
<%- model_class = Lancamento -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "Novo #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/lancamentos/show.html.erb
<%- model_class = Lancamento -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:id) %>:</strong></dt>
  <dd><%= @lancamento.id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:obra) %>:</strong></dt>
  <dd><%= Obra.find(@lancamento.obra).obra %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fornecedor) %>:</strong></dt>
  <dd><%= Fornecedore.find(@lancamento.fornecedor).fornecedor %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nota) %>:</strong></dt>
  <dd><%= @lancamento.nota %></dd>
  <dt><strong><%= model_class.human_attribute_name(:valor) %>:</strong></dt>
  <dd><%= number_to_currency(@lancamento.valor) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <% if(@lancamento.status == 0)
    @status = 'Sem Aprovação'
    @cstatus = 'status_v'
    @disable = false
  else
    @status = 'Aprovado'
    @cstatus = 'status_a'
    @disable = true
  end %>
<dd class="<%= @cstatus%>"><%= @status %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              lancamentos_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
    edit_lancamento_path(@lancamento), :class => 'btn btn-primary', :disabled => @disable %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              lancamento_path(@lancamento),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger', :disabled => @disable %>
  <%= link_to 'Produtos',
    lancamentoprodutos_path(:lancamento => @lancamento.id), :class => 'btn btn-primary' %>
  <%= link_to 'Pagamentos', pagamentos_path(:lancamento => @lancamento.id), :class => 'btn btn-warning' %>
</div>