config/routes.rb
Rails.application.routes.draw do
  resources :acessos

  resources :menusubs

  resources :menus

  devise_for :users
  get 'inicio/index'
  match "inicio/index" => "inicio#index", :via => :post
  get 'inicio/detalhes'

  get 'aprovacao/index'

  get 'aprovacao/aprovacao' => 'aprovacao#aprovacao', :as => :aprovacao

  resources :pagamentos

  resources :lancamentoprodutos

  resources :lancamentos

  resources :orcamentos

  resources :produtos

  resources :fornecedores

  resources :obras

  get 'paginas/home'

  root 'inicio#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    @Acesso = Acesso.where('user_id=?',user.id)
    if(user.id == 1)
      can :manage, :all
    else
      @Acesso.each do |acesso|

        can acesso.acao.to_sym, acesso.menusub.modulo.constantize
      end

    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/acesso.rb
class Acesso < ActiveRecord::Base
  belongs_to :user
  belongs_to :menusub
end

app/models/aprovacao.rb
class Aprovacao

end

app/models/cid.rb
class Cid < ActiveRecord::Base
end

app/models/fornecedore.rb
class Fornecedore < ActiveRecord::Base
end

app/models/inicio.rb
class Inicio
  attr_accessor :dataR

  def initialize(dataR)
    @dataR = dataR
  end

end

app/models/lancamento.rb
class Lancamento < ActiveRecord::Base

  has_many :pagamentos
end

app/models/menu.rb
class Menu < ActiveRecord::Base

  has_many :menusub
  has_many :acesso

end

app/models/menusub.rb
class Menusub < ActiveRecord::Base
  belongs_to :menu
  has_many :acesso
end

app/models/obra.rb
class Obra < ActiveRecord::Base
end

app/models/orcamento.rb
class Orcamento < ActiveRecord::Base
end

app/models/pagamento.rb
class Pagamento < ActiveRecord::Base
  attr_accessor :parcelas, :datav, :prazo
  belongs_to :lancamento
end

app/models/produto.rb
class Produto < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :acesso
end

app/controllers/aprovacao_controller.rb
class AprovacaoController < ApplicationController
  respond_to :html
  load_and_authorize_resource

  def index
    @lanc = params[:lancamento]
    if(@lanc != nil)
      Lancamento.update(@lanc,status:1)
    end
    @lancamentos = Lancamento.where(status:0).order(:created_at)
    @vencimento = '1900-01-01'.to_date
    respond_with(@lancamentos)
  end


  def aprovacao
    @lanc = params[:lancamento]
    @lancamento = Lancamento.find(@lanc)
    @produtos = Lancamentoproduto.where(lancamento:@lanc)
    @pagamentos = Pagamento.where(lancamento:@lanc)
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'Lancamento',
               layout: 'layouts/application.pdf.erb',
               :footer => {:right => '[page] de [topage]'},
               show_as_html: params[:debug].present?
      end
    end
  end


end

app/helpers/acessos_helper.rb
module AcessosHelper
end

app/helpers/aprovacao_helper.rb
module AprovacaoHelper
end

app/helpers/cids_helper.rb
module CidsHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/menusubs_helper.rb
module MenusubsHelper
end

app/helpers/obras_helper.rb
module ObrasHelper
end

app/helpers/paginas_helper.rb
module PaginasHelper
end

app/views/aprovacao/_aprovacao.html.erb
<h1>Teste</h1>

app/views/aprovacao/aprovacao.html.erb
<%- model_class = Lancamento  -%>
<div class='page-header'>
  <h2>Detalhes do Lançamento</h2>
</div>

<dl class='dl-horizontal'>
  <dt><strong><%= model_class.human_attribute_name(:lancamento) %>:</strong></dt>
  <dd><%= @lancamento.id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:obra) %>:</strong></dt>
  <dd><%= Obra.find(@lancamento.obra).obra %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fornecedor) %>:</strong></dt>
  <dd><%= Fornecedore.find(@lancamento.fornecedor).fornecedor %></dd>
  <dt><strong><%= model_class.human_attribute_name(:valor) %>:</strong></dt>
  <dd><%= number_to_currency(@lancamento.valor) %></strong></dt>
</dl>
<hr>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:produto) %></th>
      <th><%= model_class.human_attribute_name(:quantidade) %></th>
      <th><%= model_class.human_attribute_name(:valor) %></th>
      <th>Valor Total</th>
    </tr>
  </thead>
  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= Produto.find(produto.produto).descricao %></td>
        <td><%= produto.quantidade %></td>
        <td><%= number_to_currency(produto.valor) %></td>
        <td><%= number_to_currency(produto.valor * produto.quantidade) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr>
<table class='table table-striped'>
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:vencimento) %></th>
      <th><%= model_class.human_attribute_name(:valor) %></th>
    </tr>
  </thead>
  <tbody>
    <% @pagamentos.each do |pagamento| %>
      <tr>
        <td><%=l pagamento.vencimento %></td>
        <td><%= number_to_currency(pagamento.valor) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),params[:voltar], :class => 'btn btn-default' %>&nbsp;&nbsp;<%= link_to 'Imprimir','/aprovacao/aprovacao.pdf?lancamento='+@lancamento.id.to_s, :class => 'btn btn-info', :target => '_blank' %>
</div>

app/views/aprovacao/aprovacao.pdf.erb
<%- model_class = Lancamento  -%>
<div class='page-header'>
  <h2>Detalhes do Lançamento</h2>
</div>

<strong><%= model_class.human_attribute_name(:lancamento) %>:</strong>
  <%= @lancamento.id %>
<br><strong><%= model_class.human_attribute_name(:obra) %>:</strong>
  <%= Obra.find(@lancamento.obra).obra %>
<br><strong><%= model_class.human_attribute_name(:fornecedor) %>:</strong>
  <%= Fornecedore.find(@lancamento.fornecedor).fornecedor %>
<br><strong><%= model_class.human_attribute_name(:valor) %>:</strong>
  <%= number_to_currency(@lancamento.valor) %></strong>

<hr>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:produto) %></th>
      <th><%= model_class.human_attribute_name(:quantidade) %></th>
      <th><%= model_class.human_attribute_name(:valor) %></th>
      <th>Valor Total</th>
    </tr>
  </thead>
  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= Produto.find(produto.produto).descricao %></td>
        <td><%= produto.quantidade %></td>
        <td><%= number_to_currency(produto.valor) %></td>
        <td><%= number_to_currency(produto.valor * produto.quantidade) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr>
<table class='table table-striped'>
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:vencimento) %></th>
      <th><%= model_class.human_attribute_name(:valor) %></th>
    </tr>
  </thead>
  <tbody>
    <% @pagamentos.each do |pagamento| %>
      <tr>
        <td><%=l pagamento.vencimento %></td>
        <td><%= number_to_currency(pagamento.valor) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr>
<div class="form-actions">

</div>

app/views/aprovacao/index.html.erb
<%- model_class = Lancamento -%>
<div class='page-header'>
  <h1>Aprovação</h1>
</div>


<table class="table table-striped">

  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:obra) %></th>
      <th><%= model_class.human_attribute_name(:fornecedor) %></th>
      <th><%= model_class.human_attribute_name(:valor) %></th>
      <th><%= model_class.human_attribute_name(:parcelas) %></th>
      <th><%= model_class.human_attribute_name(:primeiro_vencimento) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @lancamentos.each do |lancamento| %>
      <% @pagamentos = Pagamento.where(lancamento:lancamento.id) %>

      <tr>
        <td><%= lancamento.id %></td>
        <td><%= Obra.find(lancamento.obra).obra %></td>
        <td><%= Fornecedore.find(lancamento.fornecedor).fornecedor %></td>
        <td><%= number_to_currency(lancamento.valor) %></td>
        <td><%= @pagamentos.count %></td>
        <% @pagamentos.first(1).each do |venc|
            @vencimento = venc.vencimento
            end
        %>

        <td><%=l @vencimento %></td>

        <% if(lancamento.status == 0)
             @status = 'Sem Aprovação'
             @cstatus = 'status_v'
           else
             @status = 'Aprovado'
             @cstatus = 'status_a'
           end
        %>
      <td class='<%= @cstatus %>'><%= @status %></td>
      <td><%= link_to 'Detalhes',aprovacao_path({:lancamento=>lancamento.id,:voltar=>aprovacao_index_path}), :class => 'btn btn-primary' %>&nbsp;<%= link_to 'Aprovar',aprovacao_index_path(:lancamento => lancamento.id), :class => 'btn btn-info' %> </td>
      </tr>
    <% end %>
  </tbody>

</table>