config/routes.rb
Rails.application.routes.draw do
  resources :acessos

  resources :menusubs

  resources :menus

  devise_for :users
  get 'inicio/index'
  match "inicio/index" => "inicio#index", :via => :post
  get 'inicio/detalhes'

  get 'aprovacao/index'

  get 'aprovacao/aprovacao' => 'aprovacao#aprovacao', :as => :aprovacao

  resources :pagamentos

  resources :lancamentoprodutos

  resources :lancamentos

  resources :orcamentos

  resources :produtos

  resources :fornecedores

  resources :obras

  get 'paginas/home'

  root 'inicio#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    @Acesso = Acesso.where('user_id=?',user.id)
    if(user.id == 1)
      can :manage, :all
    else
      @Acesso.each do |acesso|

        can acesso.acao.to_sym, acesso.menusub.modulo.constantize
      end

    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/acesso.rb
class Acesso < ActiveRecord::Base
  belongs_to :user
  belongs_to :menusub
end

app/models/aprovacao.rb
class Aprovacao

end

app/models/cid.rb
class Cid < ActiveRecord::Base
end

app/models/fornecedore.rb
class Fornecedore < ActiveRecord::Base
end

app/models/inicio.rb
class Inicio
  attr_accessor :dataR

  def initialize(dataR)
    @dataR = dataR
  end

end

app/models/lancamento.rb
class Lancamento < ActiveRecord::Base

  has_many :pagamentos
end

app/models/menu.rb
class Menu < ActiveRecord::Base

  has_many :menusub
  has_many :acesso

end

app/models/menusub.rb
class Menusub < ActiveRecord::Base
  belongs_to :menu
  has_many :acesso
end

app/models/obra.rb
class Obra < ActiveRecord::Base
end

app/models/orcamento.rb
class Orcamento < ActiveRecord::Base
end

app/models/pagamento.rb
class Pagamento < ActiveRecord::Base
  attr_accessor :parcelas, :datav, :prazo
  belongs_to :lancamento
end

app/models/produto.rb
class Produto < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :acesso
end

app/controllers/fornecedores_controller.rb
class FornecedoresController < ApplicationController
  before_action :set_fornecedore, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /fornecedores
  # GET /fornecedores.json
  def index
    @fornecedores = Fornecedore.all
  end

  # GET /fornecedores/1
  # GET /fornecedores/1.json
  def show
  end

  # GET /fornecedores/new
  def new
    @fornecedore = Fornecedore.new
  end

  # GET /fornecedores/1/edit
  def edit
  end

  # POST /fornecedores
  # POST /fornecedores.json
  def create
    @fornecedore = Fornecedore.new(fornecedore_params)

    respond_to do |format|
      if @fornecedore.save
        format.html { redirect_to @fornecedore, notice: 'Fornecedore was successfully created.' }
        format.json { render :show, status: :created, location: @fornecedore }
      else
        format.html { render :new }
        format.json { render json: @fornecedore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fornecedores/1
  # PATCH/PUT /fornecedores/1.json
  def update
    respond_to do |format|
      if @fornecedore.update(fornecedore_params)
        format.html { redirect_to @fornecedore, notice: 'Fornecedore was successfully updated.' }
        format.json { render :show, status: :ok, location: @fornecedore }
      else
        format.html { render :edit }
        format.json { render json: @fornecedore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fornecedores/1
  # DELETE /fornecedores/1.json
  def destroy
    @fornecedore.destroy
    respond_to do |format|
      format.html { redirect_to fornecedores_url, notice: 'Fornecedore was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fornecedore
      @fornecedore = Fornecedore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fornecedore_params
      params.require(:fornecedore).permit(:fornecedor, :contato)
    end
end

app/helpers/acessos_helper.rb
module AcessosHelper
end

app/helpers/cids_helper.rb
module CidsHelper
end

app/helpers/fornecedores_helper.rb
module FornecedoresHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/menusubs_helper.rb
module MenusubsHelper
end

app/helpers/obras_helper.rb
module ObrasHelper
end

app/helpers/paginas_helper.rb
module PaginasHelper
end

app/views/fornecedores/_form.html.erb
<%= form_for @fornecedore, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :fornecedor, :class => 'control-label' %>
    <%= f.text_field :fornecedor, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :contato, :class => 'control-label' %>
    <%= f.text_field :contato, :class => 'form-control' %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                fornecedores_path, :class => 'btn' %>
  </div>
<% end %>

app/views/fornecedores/edit.html.erb
<%- model_class = Fornecedore -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Editar #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/fornecedores/index.html.erb
<%- model_class = Fornecedore -%>
<%  if can? :edit, Fornecedore
        @edit = false
    else
        @edit = true
    end
    if can? :destroy, Fornecedore
        @del = false
    else
        @del = true
    end
    if can? :new, Fornecedore
        @new = false
    else
        @new = true
    end
%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:fornecedor) %></th>
      <th><%= model_class.human_attribute_name(:contato) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @fornecedores.each do |fornecedore| %>
      <tr>
        <td><%= link_to fornecedore.id, fornecedore_path(fornecedore) %></td>
        <td><%= fornecedore.fornecedor %></td>
        <td><%= fornecedore.contato %></td>
        <td><%=l fornecedore.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
            edit_fornecedore_path(fornecedore),:disabled => @edit, :class => 'btn btn-primary btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      fornecedore_path(fornecedore),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Deseja Excluir?')) },:disabled => @del,
                      :class => 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
  new_fornecedore_path,:disabled => @new,
            :class => 'btn btn-primary' %>

app/views/fornecedores/new.html.erb
<%- model_class = Fornecedore -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "Novo #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/fornecedores/show.html.erb
<%- model_class = Fornecedore -%>
<%  if can? :edit, Fornecedore
        @edit = false
    else
        @edit = true
    end
    if can? :destroy, Fornecedore
        @del = false
    else
        @del = true
    end
    if can? :new, Fornecedore
        @new = false
    else
        @new = true
    end
%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:fornecedor) %>:</strong></dt>
  <dd><%= @fornecedore.fornecedor %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contato) %>:</strong></dt>
  <dd><%= @fornecedore.contato %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              fornecedores_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
    edit_fornecedore_path(@fornecedore),:disabled => @edit, :class => 'btn btn-primary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              fornecedore_path(@fornecedore),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },:disabled => @del,
              :class => 'btn btn-danger' %>
</div>