config/routes.rb
Rails.application.routes.draw do
  resources :acessos

  resources :menusubs

  resources :menus

  devise_for :users
  get 'inicio/index'
  match "inicio/index" => "inicio#index", :via => :post
  get 'inicio/detalhes'

  get 'aprovacao/index'

  get 'aprovacao/aprovacao' => 'aprovacao#aprovacao', :as => :aprovacao

  resources :pagamentos

  resources :lancamentoprodutos

  resources :lancamentos

  resources :orcamentos

  resources :produtos

  resources :fornecedores

  resources :obras

  get 'paginas/home'

  root 'inicio#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    @Acesso = Acesso.where('user_id=?',user.id)
    if(user.id == 1)
      can :manage, :all
    else
      @Acesso.each do |acesso|

        can acesso.acao.to_sym, acesso.menusub.modulo.constantize
      end

    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/acesso.rb
class Acesso < ActiveRecord::Base
  belongs_to :user
  belongs_to :menusub
end

app/models/aprovacao.rb
class Aprovacao

end

app/models/cid.rb
class Cid < ActiveRecord::Base
end

app/models/fornecedore.rb
class Fornecedore < ActiveRecord::Base
end

app/models/inicio.rb
class Inicio
  attr_accessor :dataR

  def initialize(dataR)
    @dataR = dataR
  end

end

app/models/lancamento.rb
class Lancamento < ActiveRecord::Base

  has_many :pagamentos
end

app/models/menu.rb
class Menu < ActiveRecord::Base

  has_many :menusub
  has_many :acesso

end

app/models/menusub.rb
class Menusub < ActiveRecord::Base
  belongs_to :menu
  has_many :acesso
end

app/models/obra.rb
class Obra < ActiveRecord::Base
end

app/models/orcamento.rb
class Orcamento < ActiveRecord::Base
end

app/models/pagamento.rb
class Pagamento < ActiveRecord::Base
  attr_accessor :parcelas, :datav, :prazo
  belongs_to :lancamento
end

app/models/produto.rb
class Produto < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :acesso
end

app/controllers/pagamentos_controller.rb
class PagamentosController < ApplicationController
  before_action :set_pagamento, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  respond_to :html

  def index
    @lancamento = params[:lancamento]
    @pagamentos = Pagamento.where(lancamento:@lancamento)
    respond_with(@pagamentos)
  end

  def show
    respond_with(@pagamento)
  end

  def new
    if(params[:pagamento] != nil)
      @i = 0
      @parametros = params[:pagamento];
      @valor = BigDecimal.new(@parametros['total']) / @parametros['parcelas'].to_i
      @vencimento = Date.new(@parametros['datav(1i)'].to_i,@parametros['datav(2i)'].to_i,@parametros['datav(3i)'].to_i)

      while @i < @parametros['parcelas'].to_i do

        @pagamento = Pagamento.new

        @pagamento.vencimento = @vencimento
        @pagamento.valor = @valor.truncate(2)
        @vencimento = @vencimento + @parametros['prazo'].to_i
        @pagamento.lancamento_id = @parametros['lancamento'].to_i
        @pagamento.save

        @i += 1
      end
      redirect_to pagamentos_path(:lancamento => @pagamento.lancamento_id)

    end

  end

  def edit
  end

  def create
    @pagamento = Pagamento.new(pagamento_params)
    @pagamento.save
    respond_with(@pagamento)
  end

  def update
    @pagamento.update(pagamento_params)
    respond_with(@pagamento)
  end

  def destroy
    @pagamento.destroy
    redirect_to :action => 'index', :lancamento => params[:lancamento]
  end

  private
    def set_pagamento
      @pagamento = Pagamento.find(params[:id])
    end

    def pagamento_params
      params.require(:pagamento).permit(:lancamento_id, :vencimento, :valor)
    end
end

app/helpers/acessos_helper.rb
module AcessosHelper
end

app/helpers/cids_helper.rb
module CidsHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/menusubs_helper.rb
module MenusubsHelper
end

app/helpers/obras_helper.rb
module ObrasHelper
end

app/helpers/pagamentos_helper.rb
module PagamentosHelper
end

app/helpers/paginas_helper.rb
module PaginasHelper
end

app/views/pagamentos/_form.html.erb
<%= form_for @pagamento, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    Faltar Pagar:
    <%= number_to_currency(Lancamento.find(params[:lancamento]).valor - Pagamento.where(lancamento:params[:lancamento]).sum('valor')) %>
    <%= f.hidden_field :lancamento_id, :value => params[:lancamento] %>
  </div>
  <div class="form-group">
    <%= f.label :vencimento, :class => 'control-label' %>
    <%= f.date_select :vencimento, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :valor, :class => 'control-label' %>
    <%= f.text_field :valor, :class => 'form-control valor' %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
      pagamentos_path(:lancamento => params[:lancamento]), :class => 'btn' %>
  </div>
<% end %>

app/views/pagamentos/edit.html.erb
<%- model_class = Pagamento -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pagamentos/index.html.erb
<%- model_class = Pagamento -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:lancamento) %></th>
      <th><%= model_class.human_attribute_name(:vencimento) %></th>
      <th><%= model_class.human_attribute_name(:valor) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% if(Lancamento.find(params[:lancamento]).status == 0)
          @disable = false
        else
          @disable = true
        end
      %>
    <% @pagamentos.each do |pagamento| %>
      <tr>
        <td><%= link_to pagamento.id, pagamento_path(pagamento) %></td>
        <td><%= pagamento.lancamento_id %></td>
        <td><%=l pagamento.vencimento %></td>
        <td><%= number_to_currency(pagamento.valor) %></td>
        <td><%=l pagamento.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
            edit_pagamento_path(pagamento,:lancamento => pagamento.lancamento), :class => 'btn btn-primary btn-xs',:disabled=>@disable %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
            pagamentos_path(pagamento,:lancamento => pagamento.lancamento),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger btn-xs',:disabled=>@disable %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
Total da Compra: <%= number_to_currency(Lancamento.find(params[:lancamento]).valor) %>
<br>
Total do Pagamento: <%= number_to_currency(@pagamentos.sum('valor')) %>
<br>
<%
  if(Lancamento.find(params[:lancamento]).valor > @pagamentos.sum('valor'))
    @novo = false;
    @lp = Lancamento.find(params[:lancamento]).valor - @pagamentos.sum('valor')
    @mensagem = '<div class="alert alert-danger">'
    @mensagem += 'Faltar Lançar Pagamentos no Valor de '+number_to_currency(@lp)
    @mensagem += '</div>'
  else
    @novo = true
    @mensagem = ''
  end
%>

<% if(Lancamento.find(params[:lancamento]).status == 0 && @novo != true)
     @novo = false

    else
      @novo = true

    end
  %>

  <%= @mensagem.html_safe  %>

<%= link_to t('.new', :default => t("helpers.links.new")),
  new_pagamento_path(:lancamento => params[:lancamento]), :disabled => @novo,
  :class => 'btn btn-primary' %>
<%= link_to 'Voltar ao Lançamento', lancamento_path(params[:lancamento]), :class => 'btn btn-success' %>

app/views/pagamentos/new.html.erb
<%- model_class = Pagamento -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<% @Valor = Lancamento.find(params[:lancamento]).valor %>
<%= form_for :pagamento,:method => 'get' do |f| %>
  <%= f.hidden_field :lancamento, :value => params[:lancamento] %>
  <%= f.label 'Valor Total', :class => 'control-label' %>
  <%= f.hidden_field :total, :value => @Valor %>
  <%= f.label number_to_currency(@Valor), :class => 'form-control' %>
  <%= f.label 'Parcelas', :class => 'control-label' %>
  <%= f.number_field :parcelas, :class => 'form-control' %>
  <%= f.label 'Primeiro Vencimento', :class => 'control-label' %>
  <%= f.date_select :datav, {},{:class => 'form-control'} %>
  <%= f.label 'Prazo Médio', :class => 'control-label' %>
  <%= f.number_field :prazo, :class => 'form-control' %>
  <%= f.submit 'Gerar', :class => 'btn btn-primary' %>
<% end %>

app/views/pagamentos/new_old.html.erb
<%- model_class = Pagamento -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pagamentos/show.html.erb
<%- model_class = Pagamento -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:lancamento) %>:</strong></dt>
  <dd><%= @pagamento.lancamento_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:vencimento) %>:</strong></dt>
  <dd><%=l @pagamento.vencimento %></dd>
  <dt><strong><%= model_class.human_attribute_name(:valor) %>:</strong></dt>
  <dd><%= number_to_currency(@pagamento.valor) %></dd>
</dl>
<% if(Lancamento.find(@pagamento.lancamento_id).status == 0)
      @disable = false
   else
      @disable = true
   end
%>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
    pagamentos_path(:lancamento => @pagamento.lancamento_id), :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
    edit_pagamento_path(@pagamento), :class => 'btn btn-primary',:disabled=>@disable %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
    pagamento_path(@pagamento,:lancamento => @pagamento.lancamento),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger',:disabled=>@disable %>
</div>